title: Pandemic Loan Outlier Detection and Indicators (PLODI)
description: PLODI uses machine learning modelling to identify fraud risk factors and rank loans disbursed as part of the US Small Business Administration"'"s Paycheck Protection Program for investigation.
