remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pandemic Loan Outlier Detection and Indicators (PLODI)
description: Pandemic Loan Outlier Detection and Indicators (PLODI) uses machine learning to rank loans disbursed as part of the US Small Business Administration\'s Paycheck Protection Program based on their risk factors.
